# direct_task:
#   container:
#     image:  astraluma/entrypoint-debug
#   env:
#     CIRRUS_SHELL: direct
#   script:
#     - __SCRIPT_COMMAND_1__
#     - __SCRIPT_COMMAND_2__


# standard_task:
#   container:
#     image:  astraluma/entrypoint-debug
#   script:
#     - __SCRIPT_COMMAND_1__
#     - __SCRIPT_COMMAND_2__


direct_ep_task:
  container:
    image:  astraluma/entrypoint-debug
    entrypoint: ["/entrypoint"]
  env:
    CIRRUS_SHELL: direct
  script:
    - __SCRIPT_COMMAND_1__
    - __SCRIPT_COMMAND_2__


standard_ep_task:
  container:
    image:  astraluma/entrypoint-debug
    entrypoint: ["/entrypoint"]
  script:
    - __SCRIPT_COMMAND_1__
    - __SCRIPT_COMMAND_2__
