direct_task:
  container:
    image:  astraluma/entrypoint-debug
  env:
    CIRRUS_SHELL: direct
  script:
    - __SCRIPT_COMMAND_1__
    - __SCRIPT_COMMAND_2__


standard_task:
  container:
    image:  astraluma/entrypoint-debug
  script:
    - __SCRIPT_COMMAND_1__
    - __SCRIPT_COMMAND_2__


entrypoint_task:
  container:
    image:  astraluma/entrypoint-debug
  env:
    CIRRUS_SHELL: /entrypoint
  script:
    - __SCRIPT_COMMAND_1__
    - __SCRIPT_COMMAND_2__
